#!/usr/bin/env python
import rospy
import serial
from std_msgs.msg import String
from sensor_msgs.msg import Imu

ser =serial.Serial('/dev/ttyACM0',9600)

def main():
	while True:
		if(ser.in_waiting>0):
			line=ser.readline()
#			El mensaje llega Acc[3] Mag[4] Gyro[4];
			print(line)
			divided=line.split()
			print divided
			sAcc=divided[0]
			sMag=divided[1]
			sGyro=divided[2]
			msg=Imu()
			i=0
			axes=[0,0,0]
			for x in sAcc.split(','):
				axes[i]=(float(float(x)/1000)*9.81)
				i+=1
			print(axes)
def talker():
    pub = rospy.Publisher('chatter', String, queue_size=10)
    rospy.init_node('talker', anonymous=True)
    rate = rospy.Rate(10) # 10hz
    while not rospy.is_shutdown():
        hello_str = "hello world %s" % rospy.get_time()
        rospy.loginfo(hello_str)
        pub.publish(hello_str)
        rate.sleep()

if __name__ == '__main__':
    try:
        #talker()
		main()
    except rospy.ROSInterruptException:
        pass

